travis:
  secure:
    BINSTAR_TOKEN: ObKeY7g2ZywJley7eV/UKdB7oeDiwG4WHVQPtvT77PWh79nuRbrBKeRvQxLHx6OZ7BvN143nVD/k2u67nsUtQwieW9kzVU+Jr69kAgqxO6IbCrXK1h55iW/MH4iuD5L1ZyPY5aGnU2tUoaKNCtblWunBhWVnVLlk6zBiU3SjwF78PuedRgEGnSBlbK/Sy0oidzOJ6VxXg8NPzcyYH20DKalNbzUZH9p03CRVYh+EA1XAGqOEU4/p4qb8wfA5A2Ma9DSqTH4B88Bx3qCy7wqzuN0SQRKAX3x4pA5eW04uooVYvbDnII17ljyPI2umsIaqyEfgnFAe45AbwTo6RKbY5HRa/cnOVoVutc6OmRFr3a0/kii6StfHBwgTuMoYfLWtQrLKVRI6lea5WI2HBWoe0vXdm9iSBEp0bOr/0CmDll5z+G8Wzhe5OIlMwI3tC0EHPsY7DRojvLsMAxzLmOvYSFlb0+G7N9A8YLyBz2pF817JKknH/5u8deoYmqbXS11ZDq6NDP6dvp7ySyrhOuL8fm5+FSd9V9LnhP0BAbXOZAoWgNjS94lfaCda7IYUxgzMRloR+u80DPXFmzPJPxn/E3mefOH8ivWoLkZwOAZMteT1DNHniNrvGulJcn3Qtw2CeA+EBQmuPaEftUGifIaku+BxvhVmlQtbXgWUMhLdtSU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
